etonians/posts/forms.py
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length

from flask_wtf import FlaskForm


class PostForm(FlaskForm):
    title = StringField(
        label="Title",
        validators=[DataRequired(), Length(max=150, message="Title is longer than 150 characters")]
    )
    content = TextAreaField(label="Content", validators=[DataRequired()])
    submit = SubmitField(label="Post")

    def validate_long_word(self):
        # this function will be written in future commits
        pass

etonians/comments/views.py
from flask import render_template, url_for, redirect, request, flash, Blueprint, g
from flask_login import current_user, login_required

from etonians import db
from etonians.models import Comment
from etonians.comments.forms import CommentForm
from etonians.main.forms import SearchForm

comments = Blueprint("comments", __name__)


@comments.before_app_request
def before_request():
    if current_user.is_authenticated:
        g.image_file = url_for("static", filename=f"user_images/{current_user.image_file}")
        g.search_form = SearchForm()


@comments.route("/comment/id/<int:comment_id>/edit/", methods=["POST", "GET"])
@login_required
def edit_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)

    if current_user != comment.author:
        flash("You can only edit your own replies!", category="danger")
        return redirect(url_for("main.home"))
    
    form = CommentForm()
    if form.validate_on_submit():
        comment.title = form.title.data
        comment.content = form.content.data
        db.session.commit()
        flash("Your reply has successfully been edited!", category="success")
        return redirect(url_for("posts.post", post_id=comment.post.id))
    elif request.method == "GET":
        form.title.data = comment.title
        form.content.data = comment.content
    
    return render_template(
        "edit_comment.html",
        title=comment.title,
        form=form
    )


@comments.route("/comment/id/<int:comment_id>/delete/", methods=["POST", "GET"])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    post_id = comment.post.id

    if current_user != comment.author:
        flash("You can only delete your own replies!", category="danger")
        return redirect(url_for("main.home"))

    db.session.delete(comment)
    db.session.commit()

    return redirect(url_for("posts.post", post_id=post_id))

etonians/main/views.py
from datetime import datetime

from flask import render_template, url_for, redirect, Blueprint, g, current_app
from flask_login import current_user, login_required

from etonians.models import Post
from etonians.utils import convert_date
from etonians.main.forms import SearchForm

main = Blueprint("main", __name__)


@main.before_app_request
def before_request():
    if current_user.is_authenticated:
        g.image_file = url_for("static", filename=f"user_images/{current_user.image_file}")
        g.search_form = SearchForm()
        g.current_time = datetime.utcnow()


@main.route("/")
def landing_page():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    else:
        return redirect(url_for("users.user_authentication"))


@main.route("/home/")
@login_required
def home():
    posts = []

    for post in Post.query.all():
        if current_user.year_group in post.filter_year_group:
            posts.append(post)

    posts = posts[::-1]
    
    return render_template(
        "home.html",
        title="Home",
        posts=posts,
        convert_date=convert_date
    )


@main.route("/sw.js")
def service_worker():
    return current_app.send_static_file("js/sw.js")


@main.route("/no-internet")
def offline():
    return current_app.send_static_file("offline.html")


@main.route("/about/")
def about():
    if current_user.is_authenticated:
        image_file = g.image_file
    else:
        image_file = None

    return render_template(
        "about.html",
        title="About",
        image_file=image_file
    )

etonians/posts/__init__.py
# This file is intentionally left blank; it is created in order to utilise the Python package structure.

etonians/posts/routes.py
from datetime import datetime
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required

from etonians import db
from etonians.models import Post, Comment
from etonians.utils import convert_date
from etonians.posts.forms import PostForm
from etonians.comments.forms import CommentForm

posts = Blueprint("posts", __name__)


@posts.route("/post/new/", methods=["POST", "GET"])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        filter_year_group_list = request.form.getlist("filter_year_group")
        filter_year_group = ""
        
        if filter_year_group_list:
            for year_group in filter_year_group_list:
                filter_year_group += year_group
            post = Post(title=form.title.data, content=form.content.data, author=current_user, year_group=current_user.year_group, filter_year_group=filter_year_group)
            db.session.add(post)
            db.session.commit()
            flash("New post successfully created!", category="success")
            return redirect(url_for("main.home"))
        else:
            flash("Tick at least one of the year group boxes to proceed.", category="danger")

    image_file = url_for("static", filename=f"profile_pictures/{current_user.image_file}")

    return render_template("create_post.html", title="New Post", form=form, image_file=image_file)


@posts.route("/post/id/<int:post_id>/", methods=["POST", "GET"])
@login_required
def post(post_id): # every post has a unique ID
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    comments = Comment.query.filter_by(post=post)
    
    if form.validate_on_submit():
        comment = Comment(title=form.title.data, content=form.content.data, author=current_user, post=post)
        db.session.add(comment)
        db.session.commit()
        flash("Your reply has successfully been created!", category="success")
        return redirect(url_for("posts.post", post_id=post_id))
    
    current_time = datetime.utcnow()
    image_file = url_for("static", filename=f"profile_pictures/{current_user.image_file}")

    return render_template("post.html", title=post.title, form=form, post=post, comments=comments, current_time=current_time, convert_date=convert_date, image_file=image_file)


@posts.route("/post/id/<int:post_id>/edit/", methods=["POST", "GET"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user: # if a user is trying to update someone else's post, then 403 error
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data # updates the old post title and content with new title and content
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been successfully updated!", category="success")
        return redirect(url_for("main.home"))
    elif request.method == "GET": # if the user simply loads the page
        form.title.data = post.title # the boxes are already filled in with the non-updated post title and content
        form.content.data = post.content

    image_file = url_for("static", filename=f"profile_pictures/{current_user.image_file}")
    
    return render_template("update_post.html", title="Update Post", form=form, image_file=image_file)


@posts.route("/post/id/<int:post_id>/delete/", methods=["POST", "GET"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author: # if the user tries to delete someone else's post, then 403 error
        abort(403)

    for comment in Comment.query.filter_by(post_id=post.id):
        db.session.delete(comment)
        db.session.commit()

    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", category="danger")
    
    return redirect(url_for("main.home"))

etonians/posts/views.py
from datetime import datetime

import elasticsearch

from flask import render_template, url_for, flash, redirect, request, Blueprint, g
from flask_login import current_user, login_required

from etonians import db
from etonians.models import Post, Comment
from etonians.utils import convert_date
from etonians.posts.forms import PostForm
from etonians.comments.forms import CommentForm
from etonians.main.forms import SearchForm

posts = Blueprint("posts", __name__)


@posts.before_app_request
def before_request():
    if current_user.is_authenticated:
        g.image_file = url_for("static", filename=f"user_images/{current_user.image_file}")
        g.search_form = SearchForm()
        g.current_time = datetime.utcnow()


@posts.route("/post/new/", methods=["POST", "GET"])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        filter_year_group_list = request.form.getlist("filter_year_group")
        filter_year_group = ""
        
        if filter_year_group_list:
            for year_group in filter_year_group_list:
                filter_year_group += year_group

            post = Post(
                title=form.title.data,
                content=form.content.data, 
                author=current_user,
                year_group=current_user.year_group,
                filter_year_group=filter_year_group
            )
            
            db.session.add(post)
            db.session.commit()
            flash("New post successfully created!", category="success")
            return redirect(url_for("main.home"))
        else:
            flash("Tick at least one of the year group boxes to proceed.", category="danger")

    return render_template(
        "create_post.html",
        title="New Post",
        form=form
    )


@posts.route("/post/id/<int:post_id>/", methods=["POST", "GET"])
@login_required
def post(post_id): # every post has a unique ID
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    comments = Comment.query.filter_by(post=post)
    
    if form.validate_on_submit():
        comment = Comment(title=form.title.data, content=form.content.data, author=current_user, post=post)
        db.session.add(comment)
        db.session.commit()
        flash("Your reply has successfully been created!", category="success")
        return redirect(url_for("posts.post", post_id=post_id))
    
    return render_template(
        "post.html",
        title=post.title,
        form=form,
        post=post,
        comments=comments,
        convert_date=convert_date
    )


@posts.route("/post/id/<int:post_id>/edit/", methods=["POST", "GET"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    if post.author != current_user:
        flash("You can only edit your own posts!", category="danger")
        return redirect(url_for("main.home"))

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data # updates the old post title and content with new title and content
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been successfully updated!", category="success")
        return redirect(url_for("main.home"))
    elif request.method == "GET": # if the user simply loads the page
        form.title.data = post.title # the boxes are already filled in with the non-updated post title and content
        form.content.data = post.content
    
    return render_template(
        "update_post.html",
        title="Update Post",
        form=form
    )


@posts.route("/post/id/<int:post_id>/delete/", methods=["POST", "GET"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if current_user != post.author: # if the user tries to delete someone else's post, then 403 error
        flash("You can only delete your own posts!", category="danger")
        return redirect(url_for("main.home"))

    for comment in Comment.query.filter_by(post_id=post.id):
        db.session.delete(comment)
        db.session.commit()

    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", category="danger")
    
    return redirect(url_for("main.home"))


@posts.route('/search')
def search_posts():
    try:
        query = request.args.get("q")
        if not query:
            return redirect(url_for("main.home"))
            
        g.search_form.q.data = query
        posts, total = Post.search(query)
    except elasticsearch.exceptions.ConnectionError:
        flash("Sorry, the search functionality is currently under maintenance.", category="danger")
        return redirect(url_for("main.home"))

    return render_template(
        "home.html",
        title=f"({total}) {query}",
        posts=posts,
        total=total,
        convert_date=convert_date,
        search_text=query
    )

etonians/templates/account.html
{% extends "base.html" %}
{% block content %}
  <div class="col-12" id="main">
    <div class="content-section">
      <div class="media">
        <img class="account-img" src="{{ g.image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>

      <!-- the enctype attribute specifies how the form-data should be encoded when submitting it to the server -->
      <form method="POST" action="" enctype="multipart/form-data" autocomplete="off">
        {{ form.hidden_tag() }}
        <div class="form-group">
          <input type="file" accept=".png, .jpg, .jpeg, .gif" id="file" name="profile-picture" onchange="form.submit()">
          <label for="file">
            <i class="fas fa-images"></i>
            <p>Click to change your profile picture</p>
          <label>
        </div>

        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Update Profile</legend>
          <div class="form-group">
            {{ form.username.label }}
            {% if form.username.errors %}
              <!-- is-invalid class creates a red border around the textbox -->
              {{ form.username(class="form-control form-control-lg is-invalid") }}
              <!-- invalid-feedback class makes the error message red instead of black -->
              <div class="invalid-feedback">
                {% for error in form.username.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <a href="{{ url_for('users.update_password') }}">Update Password</a>
        </fieldset>

        <div class="form-group">
          <!-- "btn-outline-info" class is a button with a light blue outline -->
          {{ form.submit_button(class="btn btn-outline-info") }}
        </div>
      </form>
      <a href="{{ url_for('users.logout') }}" class="btn btn-info">Logout</a>
    </div>
  </div>
{% endblock content %}

etonians/templates/base.html
<!DOCTYPE html>
{% from "components/modal.html" import simple_modal %}
<html>
<head lang="en-GB">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no, viewport-fit=cover, user-scalable=no">
  <meta name="theme-color" content="#02AD98">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">

  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/posts.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/account.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/flashed_message.css') }}">

  <link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}">
  <link rel="apple-touch-icon" href="{{ url_for('static', filename='assets/logo_square.png') }}">
  <link rel="shortcut icon" href="#">

  <!-- If given a title in "views.py" file, then title. Otherwise, just "Etonians" -->
  {% if title %}
    <title>{{ title }} | Etonians</title>
  {% else %}
    <title>Etonians</title>
  {% endif %}
</head>

<body ontouchstart>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="flashed-message active {{ category }}">
          <div class="message-icon">
            {% if category == "danger" %}
              <span class="fas fa-exclamation-circle"></span>
            {% elif category == "warning" %}
              <span class="fas fa-exclamation-triangle"></span>
            {% elif category == "success" %}
              <span class="fas fa-check-circle"></span>
            {% else %}
              <span class="fas fa-info-circle"></span>
            {% endif %}
          </div>
          <div class="message">
            <span>{{ message }}</span>
          </div>
          <div class="close-button">
            <span><i class="fas fa-times"></i></span>
          </div>
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <div id="all-content">
    <header class="top-navbar">
      <a href="{{ url_for('main.home') }}" class="logo">
        <img src="{{ url_for('static', filename='assets/logo.png') }}">
      </a>
      
      <ul class="nav-links">
        <li class="search-bar-container"><a>
          <span><i class="far fa-search"></i></span>
        </a></li>
        <li>
          <div class="search-bar">
            <span class="back"><i class="fas fa-chevron-left"></i></span>
            <form action="{{ url_for('posts.search_posts') }}" method="GET" autocomplete="off" id="search-form">
              {{ g.search_form.q(class="text-input", placeholder="Search for keywords...", autocomplete="off") }}
            </form>
            <button type="submit" form="search-form">
              <span><i class="fas fa-search"></i></span>
            </button>
          </div>
        </li>
        <li>
          <a class="btn-solid" href="{{ url_for('posts.create_post') }}">
            <i class="fas fa-pencil-alt"></i>
            <span>New Post</span>
          </a>
        </li>
        <li class="background-darken">
          <a href="{{ url_for('main.home') }}">
            {% if request.path == "/home/" %}
              <i class="fas fa-home active"></i>
              <span class="active">Home</span>
            {% else %}
              <i class="far fa-home"></i>
              <span>Home</span>
            {% endif %}
          </a>
        </li>
      </ul>

      <div class="input-field">
        <i class="fas fa-search"></i>
        <form action="{{ url_for('posts.search_posts') }}" method="GET">
          {{ g.search_form.q(class="text-input", placeholder="Search for keywords...", autocomplete="off") }}
        </form>
      </div>

      <div class="sized-box">
        <div class="circle"></div>
      </div>

      <div class="menu-container">
        <div class="profile">
          <img src="{{ g.image_file }}">
        </div>
        <div class="menu">
          <h3>{{ current_user.username }}<br><span>Student</span></h3>
          <ul>
            <li><a href="{{ url_for('users.account') }}"><i class="fas fa-id-card"></i>Profile</a></li>
            <li><a href="#"><i class="fas fa-cog"></i>Settings</a></li>
            <li><a href="{{ url_for('users.logout') }}"><i class="fas fa-sign-out-alt"></i>Log Out</a></li>
          </ul>
        </div>
      </div>
    </header>

    <nav class="bottom-navbar">
      {% if request.path == "/home/" %}
        <a class="active">
          <i class="fas fa-home"></i>
          <span>Home</span>
        </a>
      {% else %}
        <a href="{{ url_for('main.home') }}">
          <i class="far fa-home"></i>
          <span>Home</span>
        </a>
      {% endif %}

      {% if request.path == "/account/" %}
        <a class="active">
          <i class="fas fa-user"></i>
          <span>Account</span>
        </a>
      {% else %}
        <a href="{{ url_for('users.account') }}">
          <i class="far fa-user"></i>
          <span>Account</span>
        </a>
      {% endif %}

      {% if request.path == "/account/" %}
        <a class="active">
          <i class="fas fa-cog"></i>
          <span>Settings</span>
        </a>
      {% else %}
        <a href="{{ url_for('users.account') }}">
          <i class="far fa-cog"></i>
          <span>Settings</span>
        </a>
      {% endif %}
    </nav>

    <main role="main" class="container">
      {% if total != None %}
        {{ total }}
      {% endif %}
      <div class="row">
        {% block content %}
        {% endblock content %}

        {% block sidebar %}
        {% endblock sidebar %}
      </div>
    </main>

    <footer class="footer text-center">
      <div class="row">
        <div class="social-icon text-center">
          <a href="https://www.youtube.com/simbashi" target="_blank"><span><i class="fab fa-youtube"></i></span></a>
          <a href="https://www.instagram.com/shi.simba" target="_blank"><span><i class="fab fa-instagram"></i></span></a>
          <a href="https://www.twitter.com/simba_shi" target="_blank"><span><i class="fab fa-twitter"></i></span></a>
        </div>

        <div class="copy">
          <h6>Copyright © Simba Shi 2020. All rights reserved.</h6>
        </div>
      </div>
    </footer>
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  
  <script src="{{ url_for('static', filename='js/app.js') }}"></script>
  <script src="{{ url_for('static', filename='js/flashed_message.js') }}"></script>
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  <script src="{{ url_for('static', filename='js/navbar.js') }}"></script>
</body>
</html>

etonians/templates/post.html
{% extends "base.html" %}
{% block content %}
  <div class="col-12" id="main">
    <div class="post-bar">
      <a href="javascript:historyBack()"><i class="fas fa-arrow-left"></i></a>
      <span class="btn-text">Back</span>
    </div>

    <section class="post">
      <article class="media">
        <img class="article-img" src="{{ url_for('static', filename='user_images/' + post.author.image_file) }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2 post-author" href="{{ url_for('users.user_page', username=post.author.username) }}">{{ post.author.username }}</a>
            <p class="text-muted">{{ convert_date(g.current_time, post.date_posted) }}</p>
            <div class="dropdown">
              <a class="dropdown-btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="material-icons">more_vert</span>
              </a>
        
              {% if current_user == post.author %}
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="{{ url_for('posts.update_post', post_id=post.id) }}"><span class="material-icons-outlined">edit</span><p>Edit</p></a>
                  <a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete-post-modal{{ post.id }}"><span class="material-icons-outlined">delete</span><p>Delete</p></a>
                </div>
        
                {% call simple_modal(
                  "delete-post-modal" + post.id | string,
                  "Delete Post?",
                  "Are you sure you want to delete your post? You cannot undo this action.",
                ) %}
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete Post">
                  </form>
                {% endcall %}
              {% else %}
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a href="#" class="dropdown-item"><span class="material-icons-outlined">report</span><p>Report</p></a>
                </div>
              {% endif %}
            </div>
          </div>
          <h3><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h3>
          <p class="article-content">{{ post.content }}</p>
        </div>
      </article>

      <div class="bottom-text">
        <div class="button-container">
          <label><span class="material-icons-outlined">thumb_up</span></label>
          <span>{{ post.upvotes | count }}</span>
        </div>
        <div class="button-container">
          <a href="#" data-toggle="modal" data-target="#commentModal"><span class="material-icons-outlined">comment</span></a>
          <span>{{ post.comments | count }}</span>
        </div>

        <div class="modal fade text-field-modal" id="commentModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered text-field-modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="commentModalLabel">Reply to {{ post.author.username }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form action="" method="POST" autocomplete="off" id="create-comment-form">
                  {{ form.hidden_tag() }}
                  <fieldset class="form-group mt-0">
                    <div class="form-group">
                      {{ form.title.label }}
                      {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                          {% endfor %}
                        </div>
                      {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                      {% endif %}
                      <ul class="ml-4">
                        <li><small class="text-muted">Must be less than 500 characters long.</small></li>
                      </ul>
                    </div>
          
                    <div class="form-group">
                      {{ form.content.label }}
                      {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid", rows="7", cols="100") }}
                        {% for error in errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                      {% else %}
                        {{ form.content(class="form-control", rows="7", cols="100") }}
                        <ul class="ml-4">
                          <li><small class="text-muted">This field must not be empty.</small></li>
                        </ul>
                      {% endif %}
                    </div>
                  </fieldset>
                </form>
              </div>
              <div class="modal-footer">
                <form action="" method="POST">
                  {{ form.submit(class="btn btn-info", form="create-comment-form") }}
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      {% for comment in comments %}
        <div class="comment-container">
          <img src="{{ url_for('static', filename='user_images/' + comment.author.image_file) }}">
          <a href="{{ url_for('users.user_page', username=comment.author.username) }}">{{ comment.author.username }}</a>
          <p class="comment-title">{{ comment.title }}</p>
          <p class="comment-content">{{ comment.content }}</p>
        </div>
        {% if current_user == comment.author %}
          <a href="{{ url_for('comments.edit_comment', comment_id=comment.id) }}" class="btn btn-info">Edit</a>
          <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#delete-comment-modal{{ comment.id }}">Delete</a>

          {% call simple_modal(
            "delete-comment-modal" + comment.id | string,
            "Delete Reply?",
            "Are you sure you want to delete your reply? You cannot undo this action.",
          ) %}
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('comments.delete_comment', comment_id=comment.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete Reply">
            </form>
          {% endcall %}
        {% endif %}
      {% endfor %}
    </section>
  </div>
{% endblock content %}